In [ ]:
NumPy (Numerical Python) é uma biblioteca Python usada para trabalhar com números, arrays e matrizes.
Ela é muito mais rápida e eficiente do que listas comuns quando se trata de operações matemáticas e manipulação de grandes volumes de dados.

# 1. Tipos de Dados em NumPy (DTypes)

In [ ]:
NumPy é otimizado para trabalhar com dados numéricos. Ele oferece uma gama de tipos de dados mais específicos e eficientes do que os tipos padrão do Python, o que é crucial para performance ao lidar com grandes volumes de dados.

In [20]:
# Importa a biblioteca NumPy, que é a base para computação numérica em Python.
import numpy
print("---Tipos Booleanos ---")
# numpy.bool representa um valor booleano (True ou false).
# Embora Python já tenha 'bool', Numpy oferece sua própia versão para consistência com arrays.
boolean = numpy.bool_(True)
print(boolean, type(boolean))
print("-------------------------------------------------------------------------------")
print("---tipos Strin (Bytes e Unicode---")
# Numpy possui tipos específicos para strings, úteis em arrays de texto.
#numpy.string_ armazena strings como sequências de bytes(ASCII).
string = numpy.string_("este e um texto")
print(string, type(string))
# numpy.unicode_ armazena strings como Unicode, permitindo caracteres especiais e acentos.
string = numpy.unicode_(" este é um texto")
print(string, type(string))
print("-------------------------------------------------------------------------------")
print('--- Tipos Inteiros (com e sem sinal, diferentes tamanhos')
# NumPy oferece inteiros com diferentes tamanhos de bits (8, 16, 32, 64) e opções com/sem sinal.
# 'c' geralmente indica um tipo nativo da linguagem C subjacente (como C int), que geralmente é 32 bits.
# numpy.intc: Inteiro de 32 bits, com sinal (pode ser negativo ou positivo).
inteiro = numpy.intc(-102)
# numpy.uintc: Inteiro de 32 bits, SEM sinal (apenas positivo, do 0 para cima).
uinteiro = numpy.uintc(102)

# numpy.int_ (geralmente int64 em sistemas modernos): Inteiro de 64 bits, com sinal.
long = numpy.int_(84848484)
# numpy.uint (geralmente uint64): Inteiro de 64 bits, SEM sinal.
ulong = numpy.uint(34353434)
print(inteiro, type(inteiro))
print(uinteiro, type(uinteiro))
print(long, type(long))
print(ulong, type(ulong))

print("-------------------------------------------------------------------------------")
print(" --- Tipos de Ponto Flutuante diferentes tamanhos ---")
# Similar aos inteiros, NumPy oferece floats com diferentes precisões (32 ou 64 bits).
# numpy.float_ (geralmente float64): Ponto flutuante de 64 bits (dupla precisão).
ponto_flutuante = numpy.float_(10002.34)
# numpy.float32: Ponto flutuante de 32 bits (precisão simples).
ponto_flutuante2 = numpy.float32(3994.34)

print(ponto_flutuante, type(ponto_flutuante))  
print(ponto_flutuante2, type(ponto_flutuante2))
print("-------------------------------------------------------------------------------")

print("-------------------------------------------------------------------------------")
print(" ---- Mais Exemplos de Tamanhos Específicos ---")
int8 = numpy.int8(20) # Inteiro de 8 bits (com sinal)
int16 = numpy.int16(1000)  # Inteiro de 16 bits (com sinal)
uint8 = numpy.uint8(34) # Inteiro de 8 bits (SEM sinal)
uint16 = numpy.uint16(344) # Inteiro de 16 bits (SEM sinal)
float16 = numpy.float16(16) # Ponto flutuante de 16 bits (meia precisão)

print(int8, type(int8))     # Saída: 20 <class 'numpy.int8'>
print(int16, type(int16))   # Saída: 1000 <class 'numpy.int16'>
print(uint8, type(uint8))   # Saída: 34 <class 'numpy.uint8'>
print(uint16, type(uint16)) # Saída: 344 <class 'numpy.uint16'>
print(float16, type(float16)) # Saída: 16.0 <class 'numpy.float16'>

---Tipos Booleanos ---
True <class 'numpy.bool_'>
-------------------------------------------------------------------------------
---tipos Strin (Bytes e Unicode---
b'este e um texto' <class 'numpy.bytes_'>
 este é um texto <class 'numpy.str_'>
-------------------------------------------------------------------------------
--- Tipos Inteiros (com e sem sinal, diferentes tamanhos
-102 <class 'numpy.int32'>
102 <class 'numpy.uint32'>
84848484 <class 'numpy.int64'>
34353434 <class 'numpy.uint64'>
-------------------------------------------------------------------------------
 --- Tipos de Ponto Flutuante diferentes tamanhos ---
10002.34 <class 'numpy.float64'>
3994.34 <class 'numpy.float32'>
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
 ---- Mais Exemplos de Tamanhos Específicos ---
20 <class 'numpy.int8'>
1000 <class 'numpy.int16'>
34 <class 'numpy.uint8'>
344 <class 'numpy.

 Estas são apenas anotações para referência rápida de códigos de tipo de dado,
não são códigos executáveis por si só.
i = inteiro
b = booleano
u = inteiro sem sinal (unsigned integer)
f = ponto flutuante (float)
S = String (bytes)
U = String Unicode

In [22]:
# INFORMAÇÕES ADCIONAIS
import numpy as np

print("--- Amplitude de Valores para Tipos Inteiros do NumPy ---")
print("Cuidado ao escolher tipos menores! Seus dados devem caber dentro da faixa de valores.")
print("Um 'int' padrão do Python pode ser arbitrariamente grande, mas os tipos do NumPy têm limites.")
print("-" * 70)

# --- Inteiros com Sinal (signed integers) ---
# Podem armazenar valores positivos e negativos.

# numpy.int8 (8 bits)
# Faixa de valores: -128 a 127
print(f"numpy.int8 (8 bits): Faixa de {np.iinfo(np.int8).min} a {np.iinfo(np.int8).max}")
# Exemplo de uso: Dados que representam um desvio pequeno, temperaturas limitadas.
# CUIDADO: np.array([128], dtype=np.int8) causaria um OverflowError ou truncação.

# numpy.int16 (16 bits)
# Faixa de valores: -32.768 a 32.767
print(f"numpy.int16 (16 bits): Faixa de {np.iinfo(np.int16).min} a {np.iinfo(np.int16).max}")
# Exemplo de uso: Contagens menores, pontuações de jogos, códigos de erro.

# numpy.int32 (32 bits)
# Faixa de valores: Aproximadamente -2 bilhões a 2 bilhões
print(f"numpy.int32 (32 bits): Faixa de {np.iinfo(np.int32).min} a {np.iinfo(np.int32).max}")
# Exemplo de uso: Identificadores (IDs), populações de cidades, valores financeiros comuns.

# numpy.int64 (64 bits)
# Faixa de valores: Aproximadamente -9 quintilhões a 9 quintilhões
print(f"numpy.int64 (64 bits): Faixa de {np.iinfo(np.int64).min} a {np.iinfo(np.int64).max}")
# Exemplo de uso: Contagens muito grandes, IDs de banco de dados, valores que podem exceder 32 bits.
# Este é o padrão para inteiros inferidos pelo NumPy em sistemas de 64 bits.

print("-" * 70)

# --- Inteiros Sem Sinal (unsigned integers) ---
# Podem armazenar apenas valores positivos (incluindo zero).
# Sua faixa superior é o dobro da dos inteiros com sinal do mesmo tamanho, pois não usam um bit para o sinal.

# numpy.uint8 (8 bits, sem sinal)
# Faixa de valores: 0 a 255
print(f"numpy.uint8 (8 bits): Faixa de {np.iinfo(np.uint8).min} a {np.iinfo(np.uint8).max}")
# Exemplo de uso: Pixels (RGB), valores de sensores que são sempre positivos e limitados.
# CUIDADO: np.array([-1], dtype=np.uint8) causaria um erro ou comportamento inesperado (wraps around).

# numpy.uint16 (16 bits, sem sinal)
# Faixa de valores: 0 a 65.535
print(f"numpy.uint16 (16 bits): Faixa de {np.iinfo(np.uint16).min} a {np.iinfo(np.uint16).max}")
# Exemplo de uso: Contagens de eventos, números de porta, medidas que são sempre positivas.

# numpy.uint32 (32 bits, sem sinal)
# Faixa de valores: 0 a aproximadamente 4 bilhões
print(f"numpy.uint32 (32 bits): Faixa de {np.iinfo(np.uint32).min} a {np.iinfo(np.uint32).max}")
# Exemplo de uso: Hash codes, IDs muito grandes que nunca serão negativos.

# numpy.uint64 (64 bits, sem sinal)
# Faixa de valores: 0 a aproximadamente 18 quintilhões
print(f"numpy.uint64 (64 bits): Faixa de {np.iinfo(np.uint64).min} a {np.iinfo(np.uint64).max}")
# Exemplo de uso: Contagens extremamente grandes, timestamps.

print("-" * 70)

print("--- Considerações sobre Ponto Flutuante (Floats) ---")
# Tipos de ponto flutuante lidam com precisão decimal, não apenas com a amplitude dos inteiros.
# numpy.float16 (16 bits): menor precisão e amplitude, mas economiza muita memória.
# numpy.float32 (32 bits): precisão simples.
# numpy.float64 (64 bits): dupla precisão (padrão em muitos sistemas), maior precisão e amplitude.
# A escolha aqui depende da precisão que seus cálculos exigem e do trade-off com a memória.
print(f"numpy.float16 (16 bits): Máx. valor aprox. {np.finfo(np.float16).max:.2e}, Min. valor aprox. {np.finfo(np.float16).min:.2e}, Precisão: {np.finfo(np.float16).eps:.2e}")
print(f"numpy.float32 (32 bits): Máx. valor aprox. {np.finfo(np.float32).max:.2e}, Min. valor aprox. {np.finfo(np.float32).min:.2e}, Precisão: {np.finfo(np.float32).eps:.2e}")
print(f"numpy.float64 (64 bits): Máx. valor aprox. {np.finfo(np.float64).max:.2e}, Min. valor aprox. {np.finfo(np.float64).min:.2e}, Precisão: {np.finfo(np.float64).eps:.2e}")

print("-" * 70)
print("Em resumo: para a maioria dos casos, int64 e float64 são seguros. Use tipos menores para otimização, mas SOMENTE se tiver certeza da faixa de seus dados.")

--- Amplitude de Valores para Tipos Inteiros do NumPy ---
Cuidado ao escolher tipos menores! Seus dados devem caber dentro da faixa de valores.
Um 'int' padrão do Python pode ser arbitrariamente grande, mas os tipos do NumPy têm limites.
----------------------------------------------------------------------
numpy.int8 (8 bits): Faixa de -128 a 127
numpy.int16 (16 bits): Faixa de -32768 a 32767
numpy.int32 (32 bits): Faixa de -2147483648 a 2147483647
numpy.int64 (64 bits): Faixa de -9223372036854775808 a 9223372036854775807
----------------------------------------------------------------------
numpy.uint8 (8 bits): Faixa de 0 a 255
numpy.uint16 (16 bits): Faixa de 0 a 65535
numpy.uint32 (32 bits): Faixa de 0 a 4294967295
numpy.uint64 (64 bits): Faixa de 0 a 18446744073709551615
----------------------------------------------------------------------
--- Considerações sobre Ponto Flutuante (Floats) ---
numpy.float16 (16 bits): Máx. valor aprox. 6.55e+04, Min. valor aprox. -6.55e+04, Precis

# 2. Criando Arrays NumPy (ndarray)


A base do NumPy são os objetos ndarray. Eles são como listas, mas otimizados para números, todos do mesmo tipo.

In [1]:
import numpy

print('--- Criação Básica de Array a partir de Lista Python e Inferência de Dtype ---')
# numpy.array()
# Propósito: Esta é a função mais fundamental na biblioteca NumPy. Ela é usada para
#            converter uma lista Python (ou outra sequência, como uma tupla) em um
#            array NumPy, conhecido como 'ndarray'. O 'ndarray' é a estrutura de
#            dados central do NumPy, otimizada para armazenar grandes volumes de
#            dados numéricos e realizar operações matemáticas de forma muito eficiente.
#            É o ponto de entrada para a maioria das operações NumPy.
# Atributos/Parâmetros Relevantes:
#   - 'object': O primeiro argumento, que é a sequência de dados (ex: a lista [1,2,3...])
#               que você deseja converter para um array NumPy.
#   - 'dtype': (Opcional) Permite especificar explicitamente o tipo de dado para os
#              elementos do array (ex: 'numpy.int8', 'numpy.float32'). Se você não
#              fornecer este argumento, o NumPy tentará inferir o tipo de dado mais
#              apropriado com base nos valores da lista de entrada.
array = numpy.array([1,2,3,4,5,6,7,8,9,0])
print(array)
# Saída: [1 2 3 4 5 6 7 8 9 0]

# type(array)
# Propósito: Esta é uma função built-in do Python (não específica do NumPy) que
#            retorna o tipo de um objeto. Ao aplicá-la a um array criado com NumPy,
#            ela confirma que o objeto resultante é uma instância de 'numpy.ndarray'.
#            Isso é importante para distinguir arrays NumPy de listas Python comuns.
print(type(array))
# Saída: <class 'numpy.ndarray'> (Indica que é um array NumPy)

# array.dtype
# Propósito: Este é um *atributo* de um objeto 'ndarray' do NumPy. Ele é fundamental
#            porque informa o tipo de dado dos elementos armazenados dentro do array.
#            Todos os elementos em um array NumPy devem ter o mesmo tipo de dado,
#            o que permite ao NumPy otimizar o armazenamento e as operações.
#            'int64' (inteiro de 64 bits) é um tipo de dado comum inferido para inteiros
#            em sistemas de 64 bits, pois pode armazenar uma ampla gama de valores.
print(array.dtype)
# Saída: int64 (NumPy infere o tipo de dado, neste caso, inteiro de 64 bits)
print('--- Especificando o Tipo de Dado (dtype) ao Criar o Array ---')
# numpy.array(..., dtype=numpy.int8)
# Propósito: Ao usar o argumento 'dtype' na função 'numpy.array()' e especificar
#            um tipo como 'numpy.int8', você está forçando explicitamente que
#            todos os elementos do array sejam desse tipo de dado.
#            'numpy.int8': Representa um inteiro de 8 bits. Isso significa que
#            cada número no array ocupará apenas 1 byte (8 bits) na memória,
#            em vez dos 8 bytes (64 bits) de um 'int64'. Inteiros de 8 bits podem
#            armazenar valores de -128 a 127.
# Benefícios: Essa especificação explícita é crucial para:
#            - Otimização de memória: Use tipos menores quando souber que seus dados
#              não excederão a faixa de valores do tipo escolhido.
#            - Compatibilidade: Garanta que o array tenha o tipo de dado correto
#              para interagir com outras funções, bibliotecas ou sistemas.
#            - Precisão: Escolha tipos de ponto flutuante (float32, float64) conforme
#              a precisão necessária para seus cálculos.
array = numpy.array([1,2,3,4,5,6,7,8,9,0], dtype= numpy.int8)
print(array)
# Saída: [1 2 3 4 5 6 7 8 9 0]

# type(array)
# Propósito: Confirma que o objeto criado ainda é um 'numpy.ndarray'.
print(type(array))
# Saída: <class 'numpy.ndarray'>

# array.dtype
# Propósito: Confirma que o tipo de dado dos elementos foi definido como 'int8'
#            conforme especificado.
print(array.dtype)
# Saída: int8 (Agora é um inteiro de 8 bits, economizando memória)

print('--- Arrays de Strings (Sequências de Bytes) ---')
# numpy.string_
# Propósito: 'numpy.string_' é um tipo de dado do NumPy que representa strings
#            como *sequências de bytes* de *tamanho fixo*. Diferentemente das
#            strings nativas do Python (que têm comprimento variável),
#            os arrays de strings NumPy são otimizados para armazenamento contíguo
#            e operações eficientes, o que requer que cada "slot" de string tenha
#            um tamanho predefinido. Quando você passa strings de diferentes
#            comprimentos, o NumPy ajusta o tamanho fixo para a maior string presente.
#            Strings mais curtas são preenchidas com bytes nulos; strings mais
#            longas seriam truncadas (cortadas) se o tamanho fixo fosse menor.
array = numpy.array(["1","234","1"], dtype= numpy.string_)
print(array)
# Saída: [b'1' b'234' b'1'] (Strings são armazenadas como bytes)

# type(array)
# Propósito: Confirma que o objeto é um 'numpy.ndarray'.
print(type(array))
# Saída: <class 'numpy.ndarray'>

# array.dtype
# Propósito: Neste contexto, o atributo 'array.dtype' para arrays de strings
#            de bytes terá um formato como '|S<n>', onde 'n' é o número de bytes
#            fixo alocado para cada string no array. Este 'n' é determinado
#            pela string de maior comprimento no array no momento da sua criação.
print(array.dtype)
# Saída: |S3 (Indica string de bytes de tamanho fixo 3, devido a "234")

print('--- Detalhes sobre Strings de Tamanho Fixo e Gerenciamento de Memória ---')
# 'dtype='S<n>''
# Propósito: Esta é uma sintaxe concisa para definir explicitamente o tipo de
#            dado de uma string de bytes com um *tamanho fixo* de 'n' bytes.
#            Por exemplo, 'S3' significa que cada elemento do array será uma
#            string de bytes que ocupa exatamente 3 bytes.
#            - Se você atribuir uma string menor que 3 bytes, ela será preenchida
#              com bytes nulos no final.
#            - Se você atribuir uma string maior que 3 bytes, ela será *truncada*
#              (cortada) para 3 bytes. Isso pode levar à perda de dados!
#            É uma ferramenta poderosa para gerenciar o uso da memória de forma
#            precisa, mas exige atenção aos dados para evitar truncamento.
array = numpy.array(["abc","def","ghi"], dtype= 'S3')
print(array)
# Saída: [b'abc' b'def' b'ghi']

# array.dtype
# Propósito: Confirma que o 'dtype' do array é agora explicitamente '|S3'.
#            O '|' antes do 'S3' indica que é um tipo de dado "pequeno-endian"
#            ou "big-endian" (ordem de bytes na memória), mas para strings
#            de tamanho fixo, é simplesmente uma convenção de notação.
print(array.dtype)
# Saída: |S3

# array.itemsize
# Propósito: Este é um *atributo* de um objeto 'ndarray' do NumPy. Ele retorna
#            o tamanho em bytes que *cada elemento individual* (ou "item") no array ocupa na memória.
#            Para uma string de tamanho fixo 'S3', cada string ocupa exatamente 3 bytes.
print(array.itemsize)
# Saída: 3 (Tamanho em bytes de cada item no array)

# array.nbytes
# Propósito: Este é um *atributo* de um objeto 'ndarray' do NumPy. Ele retorna
#            o tamanho *total* em bytes ocupado por *todos os dados* do array na memória.
#            É calculado como: `array.size` (número total de elementos) * `array.itemsize` (tamanho de cada elemento).
#            No exemplo: 3 itens * 3 bytes/item = 9 bytes no total.
#            Isso mostra o footprint de memória real do array.
print(array.nbytes)
# Saída: 9 (Tamanho total em bytes do array: 3 itens * 3 bytes/item)

print('--- Especificando Tamanho de Inteiros com String de Tipo (Atalhos) ---')
# 'dtype='i<n>'' (e outros atalhos de tipo como 'f<n>', 'b<n>', etc.)
# Propósito: NumPy oferece uma sintaxe de atalhos em string para especificar os tipos
#            de dados. Isso é uma alternativa mais concisa do que usar
#            'numpy.int8', 'numpy.float32', etc.
#            - 'i': indica um tipo inteiro.
#            - 'f': indica um tipo de ponto flutuante.
#            - 'S': indica um tipo de string de bytes (como visto acima).
#            - O número 'n' que segue a letra indica o número de bytes que cada
#              elemento ocupará na memória.
# Exemplos:
#   - 'i2': inteiro de 2 bytes (equivale a 'numpy.int16'). Pode armazenar valores de -32768 a 32767.
#   - 'i4': inteiro de 4 bytes (equivale a 'numpy.int32').
#   - 'f4': float de 4 bytes (equivale a 'numpy.float32', float de precisão simples).
#   - 'f8': float de 8 bytes (equivale a 'numpy.float64', float de dupla precisão).
array = numpy.array([1,2,3], dtype= 'i2')
print(array)
# Saída: [1 2 3]

# array.dtype
# Propósito: Confirma que o 'dtype' foi definido como 'int16', que é o tipo
#            completo correspondente ao atalho 'i2'.
print(array.dtype)
# Saída: int16

# array.itemsize
# Propósito: Confirma o tamanho em bytes de cada elemento. Para 'int16', é 2 bytes.
print(array.itemsize)
# Saída: 2 (Cada inteiro ocupa 2 bytes)

# array.nbytes
# Propósito: Confirma o tamanho total em bytes do array.
#            3 itens * 2 bytes/item = 6 bytes.
print(array.nbytes)
# Saída: 6 (Total de bytes: 3 itens * 2 bytes/item)

--- Criação Básica de Array a partir de Lista Python e Inferência de Dtype ---
[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int64
--- Especificando o Tipo de Dado (dtype) ao Criar o Array ---
[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int8
--- Arrays de Strings (Sequências de Bytes) ---
[b'1' b'234' b'1']
<class 'numpy.ndarray'>
|S3
--- Detalhes sobre Strings de Tamanho Fixo e Gerenciamento de Memória ---
[b'abc' b'def' b'ghi']
|S3
3
9
--- Especificando Tamanho de Inteiros com String de Tipo (Atalhos) ---
[1 2 3]
int16
2
6


# 3. Arrays de Tipos Compostos (Estruturas)
NumPy permite criar arrays onde cada elemento é uma "estrutura" ou "registro", contendo vários campos com diferentes tipos de dados. Isso é similar a structs em C ou objetos simples.

In [2]:
import numpy

# --- Array de Objetos Python Genéricos (Menos Eficiente) ---
# Propósito: Você pode colocar objetos Python arbitrários em um array NumPy.
#            No entanto, arrays de objetos geralmente perdem muitas das otimizações
#            de desempenho do NumPy, pois o NumPy não pode "entender" a estrutura
#            interna desses objetos para operações vetorizadas.
#            O dtype será 'object'.
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

array = numpy.array([Pessoa("Fernando",45),Pessoa("Rodrigo",23)])
print(array)
# Saída: [ <__main__.Pessoa object at 0x...> <__main__.Pessoa object at 0x...> ]
# Imprime as representações dos objetos na memória.

# type(array)
# Propósito: Confirma que é um 'numpy.ndarray'.
print(type(array))
# Saída: <class 'numpy.ndarray'>

# array.dtype
# Propósito: O dtype será 'object', indicando que o array armazena referências
#            a objetos Python arbitrários.
print(array.dtype, end='\n\n')
# Saída: object (Indica que o array armazena objetos Python genéricos)

# Acessando atributos dos objetos armazenados no array.
# Você pode acessar elementos do array e, em seguida, seus atributos, como em uma lista de objetos.
print(array[0].nome, array[1].idade)
# Saída: Fernando 23

# --- Array de Tipos Compostos (dtype personalizado - Mais Eficiente) ---
# Propósito: Esta é a forma "NumPy" de criar estruturas, sendo muito mais eficiente em memória e performance.
# numpy.dtype() é usado para definir uma estrutura de dados personalizada.
# Aqui, criamos um tipo 'pessoa' com dois campos:
# - 'nome': String de bytes de até 10 caracteres ('S10')
# - 'idade': Inteiro de 4 bytes ('i4')
tipo_pessoa = numpy.dtype([ ('nome','S10'),('idade','i4') ])

# numpy.array() com um dtype personalizado
# Propósito: Cria um array cujos elementos são estruturados de acordo com o 'dtype'
#            'tipo_pessoa' definido. Cada "linha" do array é uma tupla que se conforma
#            a essa estrutura.
array = numpy.array([ ('Rodrigo',24), ('fernando',45) ], dtype= tipo_pessoa)

print(array)
# Saída: [(b'Rodrigo', 24) (b'fernando', 45)]
# Note que 'nome' é convertido para bytes de tamanho fixo (S10).

# type(array)
# Propósito: Confirma que o objeto é um 'numpy.ndarray'.
print(type(array))
# Saída: <class 'numpy.ndarray'>

# array.dtype
# Propósito: Mostra a estrutura completa do dtype personalizado.
print(array.dtype)
# Saída: [('nome', '|S10'), ('idade', '<i4')]
# '<i4' indica um inteiro de 4 bytes no formato little-endian.

<class 'numpy.ndarray'>
object

Fernando 23
[(b'Rodrigo', 24) (b'fernando', 45)]
<class 'numpy.ndarray'>
[('nome', 'S10'), ('idade', '<i4')]


# 4. Atributos Essenciais do Array NumPy

Como já discutimos, os arrays NumPy (ndarray) são mais do que apenas coleções de números; eles são objetos ricos em metadados que descrevem sua estrutura e o tipo de dados que contêm. Acessar esses atributos é fundamental para programar eficientemente com NumPy.

In [3]:
import numpy as np # np é o apelido padrão para numpy

# --- Array 1D (Vetor) ---
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)
# Saída: [1 2 3 4 5 6 7 8 9 0]

# array.ndim
# Propósito: Atributo que retorna o número de dimensões (eixos) do array.
#            Para um array simples como este, é 1.
print(array.ndim)
# Saída: 1

# array.size
# Propósito: Atributo que retorna o número total de elementos no array.
#            Aqui, há 10 elementos.
print(array.size)
# Saída: 10

# len(array)
# Propósito: A função built-in 'len()' retorna o comprimento da primeira dimensão
#            do array. Para arrays 1D, é equivalente a 'array.size'.
print(len(array))
# Saída: 10

# array.shape
# Propósito: Atributo que retorna uma tupla indicando o tamanho de cada dimensão do array.
#            Para um array 1D com 10 elementos, a forma é (10,).
print(array.shape)
# Saída: (10,)

# array.dtype
# Propósito: Tipo de dado dos elementos (inferido como int64).
print(array.dtype)
# Saída: int64

# array.itemsize
# Propósito: Tamanho em bytes de cada elemento (8 bytes para int64).
print(array.itemsize)
# Saída: 8

# array.nbytes
# Propósito: Tamanho total do array em bytes (size * itemsize).
#            10 elementos * 8 bytes/elemento = 80 bytes.
print(array.nbytes)
# Saída: 80

# --- Array 2D (Matriz) ---
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
# Saída:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# array.ndim
# Propósito: Número de dimensões (2 para matriz).
print(array.ndim)
# Saída: 2

# array.size
# Propósito: Número total de elementos (3 linhas * 3 colunas = 9 elementos).
print(array.size)
# Saída: 9

# len(array)
# Propósito: Retorna o número de linhas (tamanho da primeira dimensão).
print(len(array))
# Saída: 3

# array.shape
# Propósito: Formato/dimensões (linhas, colunas).
print(array.shape)
# Saída: (3, 3)

# array.dtype
# Propósito: Tipo de dado dos elementos (inferido como int64).
print(array.dtype)
# Saída: int64

# array.itemsize
# Propósito: Tamanho em bytes de cada elemento (8 bytes para int64).
print(array.itemsize)
# Saída: 8

# array.nbytes
# Propósito: Tamanho total do array em bytes (9 * 8 = 72 bytes).
print(array.nbytes)
# Saída: 72

# --- Atributos de Array com Tipo Composto ---
# Reafirmando os atributos para um array com dtype personalizado:
tipo_pessoa = numpy.dtype([ ('nome','S10'),('idade','i4') ])
array = numpy.array([ ('Rodrigo',24), ('fernando',45) ], dtype= tipo_pessoa)
print(array)
# Saída: [(b'Rodrigo', 24) (b'fernando', 45)]

# array.ndim
# Propósito: Embora pareça uma estrutura de dados mais complexa, este array é
#            considerado 1-dimensional no NumPy porque cada "item" do array
#            é um registro completo (uma tupla estruturada), e o array é uma
#            sequência desses registros.
print(array.ndim)
# Saída: 1

# array.size
# Propósito: Número total de registros (elementos) no array.
print(array.size)
# Saída: 2

# array.shape
# Propósito: Tupla representando a forma. (2,) indica 2 elementos em uma dimensão.
print(array.shape)
# Saída: (2,)

# array.dtype
# Propósito: Mostra a definição completa do dtype estruturado.
print(array.dtype)
# Saída: [('nome', '|S10'), ('idade', '<i4')]

# array.itemsize
# Propósito: Tamanho em bytes de cada *registro* (item completo) no array.
#            Para ('nome','S10') e ('idade','i4'), é 10 bytes (nome) + 4 bytes (idade) = 14 bytes.
print(array.itemsize)
# Saída: 14

# array.nbytes
# Propósito: Tamanho total em bytes do array (2 registros * 14 bytes/registro = 28 bytes).
print(array.nbytes)
# Saída: 28

[1 2 3 4 5 6 7 8 9 0]
1
10
10
(10,)
int64
8
80
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
3
(3, 3)
int64
8
72
[(b'Rodrigo', 24) (b'fernando', 45)]
1
2
(2,)
[('nome', 'S10'), ('idade', '<i4')]
14
28


# 5. Funções de Criação de Arrays Específicos

NumPy fornece uma série de funções pré-construídas para criar arrays de forma eficiente e conveniente, sem a necessidade de preenchê-los manualmente ou converter listas Python. Essas funções são otimizadas e preferíveis para arrays maiores.

In [11]:
import numpy

# --- Arrays Preenchidos com Zeros, Uns, Vazios ou Matriz Identidade ---

# numpy.zeros(shape, dtype=float)
# Propósito: Cria um array preenchido com zeros. Útil para inicializar arrays.
#            O dtype padrão é 'float64' se não for especificado.
#            Cria um array 1D com 9 zeros.
array1 = numpy.zeros(9)
print(array1, end='\n\n')
# Saída: [0. 0. 0. 0. 0. 0. 0. 0. 0.] (Elementos são floats por padrão)

# numpy.ones(shape, dtype=float)
# Propósito: Cria um array preenchido com uns. Útil para inicializar arrays.
#            O dtype padrão é 'float64'.
#            Cria um array 1D com 3 uns.
array2 = numpy.ones(3)
print(array2, end='\n\n')
# Saída: [1. 1. 1.] (Elementos são floats por padrão)

# numpy.empty(shape, dtype=float)
# Propósito: Cria um array sem inicializar seus elementos com valores específicos.
#            Os elementos conterão lixo de memória. É a forma mais rápida de
#            criar um array com um dado tamanho, pois não há sobrecarga para preenchê-lo.
#            Cria um array 1D com 6 elementos não inicializados.
array3 = numpy.empty(6)
print(array3, end='\n\n')
# Saída: Ex: [3.35974916e-316 0.00000000e+000 ...] (Valores aleatórios/lixo)

# numpy.identity(n, dtype=float)
# Propósito: Cria uma matriz identidade quadrada (matriz onde a diagonal principal
#            é 1 e todos os outros elementos são 0).
#            'n' é o número de linhas/colunas.
#            Cria uma matriz identidade 4x4.
array4 = numpy.identity(4)
print(array4, end='\n\n')
# Saída:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

# --- Criação de Matrizes (2D) de Zeros e Uns ---
# Para criar matrizes, passe uma tupla para o argumento 'shape'.

# numpy.zeros((rows, cols))
# Propósito: Cria uma matriz 2D preenchida com zeros.
array1 = numpy.zeros((3,3))
print(array1, end='\n\n')
# Saída:
# [[0. 0. 0.]
#  [0. 0. 0.]
#  [0. 0. 0.]]

# numpy.ones((rows, cols))
# Propósito: Cria uma matriz 2D preenchida com uns.
array2 = numpy.ones((4,4))
print(array2, end='\n\n')
# Saída:
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

# --- Arrays com Sequências de Números (arange) ---

# numpy.arange(stop)
# Propósito: Cria um array 1D com valores que vão de 0 (inclusive) até 'stop' (exclusive),
#            com passo de 1. Similar à função 'range()' do Python.
array1 = numpy.arange(9)
print(array1)
# Saída: [0 1 2 3 4 5 6 7 8]

# numpy.arange(start, stop)
# Propósito: Cria um array 1D com valores que vão de 'start' (inclusive) até 'stop' (exclusive),
#            com passo de 1.
array2 = numpy.arange(4,16)
print(array2)
# Saída: [ 4  5  6  7  8  9 10 11 12 13 14 15]

# numpy.arange(start, stop, step)
# Propósito: Cria um array 1D com valores que vão de 'start' (inclusive) até 'stop' (exclusive),
#            com um 'step' (passo) especificado.
#            Neste exemplo, o 'stop' é 16+1=17 para incluir o 16, e o passo é 2.
array1 = numpy.arange(2,16+1,2)
print(array1)
# Saída: [ 2  4  6  8 10 12 14 16]

# --- Arrays Preenchidos com um Valor Constante (full) ---
# numpy.full(shape, fill_value, dtype=None)
# Propósito: Cria um array de uma dada 'shape' (forma) preenchido com um 'fill_value' (valor).
#            É mais flexível que 'zeros' ou 'ones' pois pode preencher com qualquer valor.
#            Cria uma matriz 4x4 preenchida com o número 10.
array = numpy.full((4,4), 10)
print(array)
# Saída:
# [[10 10 10 10]
#  [10 10 10 10]
#  [10 10 10 10]
#  [10 10 10 10]]

# --- Arrays com Números Aleatórios ---

# numpy.random.rand(d0, d1, ..., dn)
# Propósito: Gera um array de números aleatórios de ponto flutuante no intervalo [0.0, 1.0).
#            Os argumentos são as dimensões do array.
#            Cria uma matriz 4x4 de floats aleatórios.
array_float = numpy.random.rand(4,4)
print(array_float)
# Saída (valores variam):
# Ex: [[0.491... 0.083...] ...] (Valores float aleatórios)

# numpy.random.randint(low, high=None, size=None, dtype=int)
# Propósito: Gera um array de inteiros aleatórios no intervalo [low, high) (inclusive 'low', exclusive 'high').
#            'size' define a forma do array.
#            Cria uma matriz 5x5 de inteiros aleatórios entre 5 (inclusive) e 11 (exclusive), ou seja, de 5 a 10.
import numpy

# numpy.random.randint(low, high=None, size=None, dtype=int)
# Propósito: Gera um array de inteiros aleatórios no intervalo [low, high) (inclusive 'low', exclusive 'high').
#            'size' define a forma do array.

# Cria uma matriz 5x5 de inteiros aleatórios.
# Os números serão gerados entre 5 (inclusive) e 11 (exclusive), ou seja, de 5 a 10.
array_int = numpy.random.randint(
    5,      # low: limite inferior (inclusive) - o menor número possível é 5
    11,     # high: limite superior (exclusive) - o maior número possível é 10 (11 não incluído)
    (5,5)   # size: formato do array resultante (5 linhas, 5 colunas)
)
print(array_int)

# Saída (os valores exatos variam a cada execução, mas estarão entre 5 e 10):
# Ex: [[ 8  9 10  9  8]
#      [ 7  5  6 10  7]
#      [ 9  8  5  6  9]
#      [ 6 10  7  5  8]
#      [ 5  9  6 10  7]]

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1. 1. 1.]

[2.48059294e-316 0.00000000e+000 6.44066248e-310 6.44066248e-310
 2.55333442e-316 6.44072383e-310]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[0 1 2 3 4 5 6 7 8]
[ 4  5  6  7  8  9 10 11 12 13 14 15]
[ 2  4  6  8 10 12 14 16]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0.69473856 0.79429949 0.31835055 0.51824693]
 [0.82135417 0.62015457 0.52749695 0.416511  ]
 [0.2764628  0.70397281 0.85152101 0.07649637]
 [0.43024854 0.596945   0.05580136 0.27714116]]
[[ 6  6  8  6  8]
 [ 9  6  7  8  7]
 [10  9  5 10  6]
 [ 7 10 10 10  8]
 [10  8  9  7  6]]


# 6. Inicializando Arrays com Compreensões de Lista
Você também pode usar compreensões de lista Python para criar listas e depois convertê-las em arrays NumPy.

In [12]:
import numpy

# --- Array 1D com Compreensão de Lista ---
# Propósito: Uma forma comum e Pythonica de criar uma lista (e depois um array NumPy)
#            com base em uma sequência, aplicando uma expressão para cada item.
#            Aqui, cria um array 1D com números de 0 a 9.
array = numpy.array([i for i in range(0,10)])
print(array)
# Saída: [0 1 2 3 4 5 6 7 8 9]

# --- Array 2D (Matriz) com Compreensão de Lista Aninhada ---
# Propósito: Usa list comprehensions para criar uma lista de listas, que então
#            é convertida em um array NumPy 2D (matriz).
#            Cria uma matriz 3x3 com números sequenciais de 0 a 8.
array = numpy.array([
    [i for i in range(0,3)], # [0, 1, 2]
    [i for i in range(3,6)], # [3, 4, 5]
    [i for i in range(6,9)]  # [6, 7, 8]
    ])
print(array)
# Saída:
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 7. Indexação e Fatiamento (Slicing) de Arrays
Acessar elementos ou sub-arrays é uma operação fundamental.



In [9]:
import numpy as np

# --- Indexação em Array 1D ---
array = np.array([1,2,3,4,5,6,7,8,9,10])

# array[index]
# Propósito: Acessa um único elemento do array usando seu índice (base 0).
print(array[2])
# Saída: 3 (Elemento na posição de índice 2 é o terceiro elemento)

# array[start:end]
# Propósito: Fatiamento (slicing) de arrays. Retorna um novo array contendo
#            elementos do 'start' (inclusive) até o 'end' (exclusive).
print(array[2:4])
# Saída: [3 4] (Elementos nas posições de índice 2 e 3)

# --- Indexação em Array 2D (Matriz) ---
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array, end='\n\n')
# Saída:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# array[row_index]
# Propósito: Acessa uma linha inteira da matriz pelo seu índice.
print(array[2])
# Saída: [7 8 9] (A terceira linha)

# array[row_index][col_index]
# Propósito: Acessa um elemento específico usando notação de indexação em cascata.
print(array[2][2])
# Saída: 9 (Elemento na terceira linha, terceira coluna)

# array[row_index, col_index]
# Propósito: Acessa um elemento específico usando a notação de vírgula, que é
#            a forma preferida e mais eficiente no NumPy para indexação multidimensional.
print(array[2,2])
# Saída: 9 (Mesmo resultado, forma preferida)

# array[start_row:end_row]
# Propósito: Fatiamento de linhas. Retorna um sub-array contendo as linhas
#            do 'start_row' (inclusive) até o 'end_row' (exclusive).
print(array[1:3])
# Saída:
# [[4 5 6]
#  [7 8 9]] (Linhas de índice 1 e 2)

# array[row_index, start_col:end_col]
# Propósito: Fatiamento de colunas dentro de uma linha específica.
#            Retorna um sub-array de elementos da linha 'row_index',
#            do 'start_col' (inclusive) até o 'end_col' (exclusive).
print(array[2,1:3])
# Saída: [8 9] (Elementos da terceira linha, colunas de índice 1 e 2)

# --- Selecionando Linhas e Colunas Completas ---
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array, end='\n\n')
# Saída:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# array[row_index, :]
# Propósito: Acessa uma linha inteira. O ':' significa "todas as colunas".
print(array[2, :])
# Saída: [7 8 9] (A terceira linha completa)

# array[:, col_index]
# Propósito: Acessa uma coluna inteira. O ':' significa "todas as linhas".
print(array[:,2])
# Saída: [3 6 9] (A terceira coluna completa)

# --- Mais Exemplos de Fatiamento 2D ---
array = np.array([[1,2,3,4],[5,6,7,8]])
print(array, end='\n\n')
# Saída:
# [[1 2 3 4]
#  [5 6 7 8]]

# array[row_index, :]
# Propósito: Acessa a segunda linha completa.
print(array[1, :])
# Saída: [5 6 7 8]

# array[:, col_index]
# Propósito: Acessa a segunda coluna completa.
print(array[:,1])
# Saída: [2 6]

# --- Fatiamento com Passo (Step) ---
array = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18],
                  [19,20,21,22,23,24,25,26,27]])
print(array, end='\n\n')
# Saída: (uma matriz 3x9)
# [[ 1  2  3  4  5  6  7  8  9]
#  [10 11 12 13 14 15 16 17 18]
#  [19 20 21 22 23 24 25 26 27]]

# array[row_index, ::step]
# Propósito: Fatia uma linha específica, pegando elementos a cada 'step'.
#            Aqui, pega a segunda linha (índice 1) e depois elementos a cada 2 posições.
print(array[1, ::2])
# Saída: [10 12 14 16 18] (Elementos 10, 12, 14, 16, 18 da segunda linha)



3
[3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]
9
9
[[4 5 6]
 [7 8 9]]
[8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9]
[3 6 9]
[[1 2 3 4]
 [5 6 7 8]]

[5 6 7 8]
[2 6]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

[10 12 14 16 18]


# 8. Iterando sobre Arrays
Você pode percorrer os elementos de um array, seja de forma simples ou controlando a ordem.

In [13]:
import numpy as np

# --- Iterando sobre um Array 1D ---
array = np.array([1,2,3,4])
# Propósito: Loop 'for' padrão em Python itera sobre os elementos de arrays 1D.
for i in array:
  print(i)
# Saída:
# 1
# 2
# 3
# 4

# --- Iterando sobre um Array 2D com Loops Aninhados ---
# Por padrão, um loop 'for i in array' em um 2D array itera sobre as *linhas* do array.
array = np.array([[1,2,3,4],[5,6,7,8]])

for i in array: # 'i' será cada linha (um array 1D)
  for j in i:   # 'j' será cada elemento dentro da linha 'i'
    print(j)
# Saída:
# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8

# --- Iterando com np.nditer (Controle de Ordem) ---
# np.nditer()
# Propósito: Um iterador flexível e eficiente para arrays NumPy de N dimensões.
#            É o método preferido para iterar sobre arrays grandes, especialmente
#            quando o desempenho é crítico ou quando se lida com arrays de muitas dimensões.
# Parâmetro 'order':
#   - 'C' (C-order / row-major): Itera os elementos linha por linha (padrão).
#   - 'F' (Fortran-order / column-major): Itera os elementos coluna por coluna.
array = np.array([[1,2,3,4],[5,6,7,8]])

# Itera sobre o array em ordem Fortran (coluna por coluna).
for x in np.nditer(array, order='F'):
  print(x)
# Saída:
# 1 (coluna 0, linha 0)
# 5 (coluna 0, linha 1)
# 2 (coluna 1, linha 0)
# 6 (coluna 1, linha 1)
# 3 (coluna 2, linha 0)
# 7 (coluna 2, linha 1)
# 4 (coluna 3, linha 0)
# 8 (coluna 3, linha 1)

1
2
3
4
1
2
3
4
5
6
7
8
1
5
2
6
3
7
4
8


# 9. Modificando Elementos e Fatias de Arrays
Arrays NumPy são mutáveis, o que significa que você pode alterar seus elementos após a criação.

In [27]:
import numpy as np

# --- Modificando Elementos por Índice ---
array = np.array([[1,2,3],[5,6,7],[7,8,9]])
print(array, end='\n\n')
# Saída:
# [[1 2 3]
#  [5 6 7]
#  [7 8 9]]

# array[index] = new_value
# Propósito: Atribui uma nova lista/array a uma linha inteira (ou elemento em 1D).
array[0] = [1,2,4] # A primeira linha agora é [1,2,4]

# array[row_index, start_col:end_col] = new_values
# Propósito: Atribui novos valores a uma fatia específica de uma linha.
array[1,1:3] = [0,0] # Na segunda linha (índice 1), colunas de 1 a 2 (exclusive), define como 0,0.
                     # A segunda linha era [5,6,7] e agora é [5,0,0].

# array[row_index, col_index] = new_value
# Propósito: Atribui um novo valor a um único elemento.
array[0,0] = 10 # O elemento na primeira linha, primeira coluna agora é 10.

print(array)
# Saída:
# [[10  2  4] (Linha 0 modificada)
#  [ 5  0  0] (Linha 1 modificada)
#  [ 7  8  9]] (Linha 2 original)

# --- Modificando Colunas Inteiras ---
array = np.array([[1,2,3],[5,6,7],[7,8,9]])

# array[:, col_index] = new_values
# Propósito: Atribui uma nova lista/array a uma coluna inteira.
#            O ':' significa todas as linhas, e '2' é o índice da terceira coluna.
array[:,2] =[0,0,0] # Define a terceira coluna para ser [0,0,0].

print(array)
# Saída:
# [[1 2 0]
#  [5 6 0]
#  [7 8 0]]


[[1 2 3]
 [5 6 7]
 [7 8 9]]

[[10  2  4]
 [ 5  0  0]
 [ 7  8  9]]
[[1 2 0]
 [5 6 0]
 [7 8 0]]


# 10. Adicionando, Inserindo e Deletando Elementos
NumPy fornece funções para modificar a estrutura de um array, embora essas operações geralmente criem cópias do array.

In [13]:
import numpy as np

# --- Adicionando Elementos (np.append) ---

# np.append(array, values, axis=None)
# Propósito: Adiciona valores ao final de um array.
#            Por padrão (axis=None), o array de entrada é achatado (flattened)
#            e os valores são adicionados ao final do array achatado,
#            retornando um novo array 1D.
array = np.array([1,2,3,4])
array2 = np.append(array, [5,6,7,8])
print(array2)
# Saída: [1 2 3 4 5 6 7 8]

# np.append() em array 2D sem especificar 'axis'
array = np.array([[1,2,3],[5,6,7],[7,8,9]])
print(array, end='\n\n')
# Saída:
# [[1 2 3]
#  [5 6 7]
#  [7 8 9]]

# Propósito: Quando 'axis' não é especificado para um array multidimensional,
#            o array é achatado antes que os valores sejam anexados, resultando
#            em um novo array 1D.
array2 = np.append(array, [5,6,7])
print(array2)
# Saída: [1 2 3 5 6 7 7 8 9 5 6 7] (Array original achatado + novos valores)


# Adicionando Linhas (axis=0) ou Colunas (axis=1) a Arrays 2D

# axis=0 (adicionar como nova linha)
# Propósito: Anexa a 'values' como uma nova linha (ao longo do eixo 0).
#            Os 'values' devem ter o mesmo número de colunas que o array original.
array1 = np.append(array,[[10,11,12]], axis=0) # Adiciona uma nova linha

array2 = np.append(array,[[10],[11],[12]], axis = 1) # Adiciona uma nova coluna

print(array1, end='\n\n')
# Saída:
# [[ 1  2  3]
#  [ 4  5  6]
#  [ 7  8  9]
#  [10 11 12]]

print(array2, end='\n\n')
# Saída:
# [[ 1  2  3 10]
#  [ 4  5  6 11]
#  [ 7  8  9 12]]

# --- Deletando Elementos (np.delete) ---

# np.delete(array, obj, axis=None)
# Propósito: Remove elementos de um array. 'obj' é o índice (ou fatiamento)
#            dos elementos a serem removidos.
array = np.array([[1,2,3],[7,8,9],[10,11,12]])

# axis=0 (deletar linha)
# Propósito: Remove uma linha inteira do array.
#            Aqui, remove a linha de índice 1.
array1 = np.delete(array,1, axis = 0)
print(array1, end='\n\n')
# Saída:
# [[ 1  2  3]
#  [10 11 12]] (Linha do meio removida)

# axis=1 (deletar coluna)
# Propósito: Remove uma coluna inteira do array.
#            Aqui, remove a coluna de índice 1.
array2 = np.delete(array,1, axis = 1)

print(array2, end='\n\n')
# Saída:
# [[ 1  3]
#  [ 7  9]
#  [10 12]] (Coluna do meio removida)

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [5 6 7]
 [7 8 9]]

[1 2 3 5 6 7 7 8 9 5 6 7]
[[ 1  2  3]
 [ 5  6  7]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3 10]
 [ 5  6  7 11]
 [ 7  8  9 12]]

[[ 1  2  3]
 [10 11 12]]

[[ 1  3]
 [ 7  9]
 [10 12]]



# 11. Cópias e Views (Visualizações) de Arrays
Compreender como o NumPy lida com cópias é crucial para evitar surpresas.

In [14]:
import numpy as np

# --- Atribuição Simples (View/Referência) ---
# Propósito: Quando você faz 'copy_array = array', 'copy_array' NÃO é uma cópia independente,
#            mas sim uma *referência* ao mesmo objeto de array na memória que 'array'.
#            Qualquer modificação em 'copy_array' afetará 'array', e vice-versa.
array = np.array([1,2,3])
copy_array = array
copy_array[0] = 0 # Modifica o primeiro elemento de 'copy_array'
print(array)
# Saída: [0 2 3] (array original também é modificado)

# --- Fazendo uma Cópia Explícita (.copy()) ---
# Propósito: O método '.copy()' cria uma *cópia independente* do array.
#            As modificações feitas na cópia não afetam o array original.
array = np.array([1,2,3])
copy_array = array.copy() # Cria uma CÓPIA real dos dados.
copy_array[0] = 0 # Altera a CÓPIA, não o array original.
print(array)
# Saída: [1 2 3] (array original permanece inalterado)

[0 2 3]
[1 2 3]


# 12. Remodelagem (Reshaping) de Arrays
Mudar as dimensões de um array sem alterar seus dados.

In [20]:
import numpy as np

# --- Remodelando para 1D (achatar) ---

# array.reshape(new_shape)
# Propósito: Altera a forma (dimensões) de um array sem alterar seus dados.
#            O número total de elementos no novo shape deve ser o mesmo que o original.
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
# Saída:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Acha o array em um vetor 1D de 9 elementos.
array = array.reshape(9)
print(array)
# Saída: [1 2 3 4 5 6 7 8 9]

# --- Remodelando para Múltiplas Dimensões ---
array = np.array([i for i in range(0,27)]) # Array 1D de 0 a 26
print(array)
# Saída: [ 0  1  2 ... 24 25 26]

# Reshape para uma matriz 3x9 (3 linhas, 9 colunas)
array = array.reshape(3,9)
print(array)
# Saída:
# [[ 0  1  2  3  4  5  6  7  8]
#  [ 9 10 11 12 13 14 15 16 17]
#  [18 19 20 21 22 23 24 25 26]]

# Reshape para uma matriz 9x3 (9 linhas, 3 colunas)
array = array.reshape(9,3)
print(array)
# Saída:
# [[ 0  1  2]
#  [ 3  4  5]
#  [ 6  7  8]
#  [ 9 10 11]
#  [12 13 14]
#  [15 16 17]
#  [18 19 20]
#  [21 22 23]
#  [24 25 26]]

# Reshape para um array 3D (3 "camadas", cada uma 3x3)
array = array.reshape(3,3,3)
print(array)
# Saída:
# [[[ 0  1  2]
#   [ 3  4  5]
#   [ 6  7  8]]

#  [[ 9 10 11]
#   [12 13 14]
#   [15 16 17]]

#  [[18 19 20]
#   [21 22 23]
#   [24 25 26]]]



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


# 13. Operações Aritméticas e Lógicas em Arrays
Uma das maiores vantagens do NumPy é a capacidade de realizar operações elemento a elemento de forma vetorizada, o que é muito mais rápido do que loops Python.





In [34]:
import numpy as np

# --- Operações Aritméticas Elemento a Elemento (com arrays de mesma forma) ---
# Propósito: Realizam operações matemáticas entre arrays de mesma forma,
#            aplicando a operação a cada par de elementos correspondentes.
#            Isso é conhecido como "vetorização" e é muito eficiente.

array1 = np.array([1,2,3,4])
array2 = np.array([2,4,6,8])
print(array1 + array2) # Soma elemento a elemento: [ 3  6  9 12]
print(array1 - array2)  # Subtração elemento a elemento: [-1 -2 -3 -4]
print(array1 / array2)  # Divisão elemento a elemento: [0.5 0.5 0.5 0.5]
print(array1 * array2)   # Multiplicação elemento a elemento: [ 2  8 18 32]
print(array1 ** array2) # Potenciação (array1 elevado a array2): [  1  16 729 4096]
print(array1 // array2) # Divisão inteira (floor division) elemento a elemento: [0 0 0 0]

# Propósito: NumPy pode realizar operações entre arrays de formas diferentes,
#            desde que sejam compatíveis por regras de broadcasting.
#            O array de menor dimensão é "esticado" (replicado) para ter a mesma
#            forma do array de maior dimensão, permitindo a operação.

# Array 1D - Forma (3,)
# Para o broadcasting com um array 2D, o NumPy implicitamente o compara como (1, 3).
array1 = np.array([1, 1, 1])

# Array 2D - Forma (2,3)
array2 = np.array([[2, 4, 6],
                   [1, 2, 3]])

# O broadcasting funciona aqui porque as dimensões são compatíveis (comparando da direita para a esquerda):
# - Última dimensão: 3 (de array1) e 3 (de array2) são iguais.
# - Primeira dimensão: array1 é implicitamente (1) e array2 é (2). O 1 pode ser esticado para 2.
# array1 é esticado (replicado verticalmente) para [[1,1,1],[1,1,1]] antes da soma.
print(array1 + array2)
# Saída Esperada:
# [[3 5 7]
#  [2 3 4]]

# O próximo exemplo NÃO FUNCIONARÁ devido à AMBIGUIDADE do broadcasting.
# array1 é (3,), array3 é (3,3).
# Ao comparar (3,) com (3,3), o NumPy não consegue decidir se o (3,) deve
# ser replicado como uma "linha" (aplicado a cada linha) ou como uma "coluna"
# (aplicado a cada coluna). Essa incerteza gera o erro.
array3 = np.array([[2, 4, 6],
                   [1, 2, 3],
                   [3, 4, 5]])
# print(array1 + array3) # Isso causaria um erro de broadcasting:
                         # ValueError: operands could not be broadcast together with shapes (3,) (3,3)

# --- Operações com Escalares ---
# Propósito: Um escalar (número único) pode ser operado com um array inteiro.
#            O escalar é aplicado a cada elemento do array.
array1 = np.array([1,2,3])
print(array1 + 2) # Soma 2 a cada elemento: [3 4 5]
print(array1 - 2) # Subtrai 2 de cada elemento: [-1  0  1]

# --- Operações de Comparação Lógica ---
# Propósito: Retornam arrays booleanos (True/False) com base na comparação elemento a elemento.
array1 = np.array([10,20,30,5])
array2 = np.array([20,40,10,5])

print(array1 > array2)  # Compara se elemento de array1 é MAIOR que elemento de array2.
                        # [False False  True False] (10>20 F, 20>40 F, 30>10 T, 5>5 F)
print(array1 == array2) # Compara se elemento de array1 é IGUAL ao elemento de array2.
                        # [False False False  True]
print(array1 != array2) # Compara se elemento de array1 é DIFERENTE do elemento de array2.
                        # [ True  True  True False]

# --- Comparando Arrays Inteiros (np.array_equal) ---
# Propósito: Verifica se dois arrays são idênticos em forma E conteúdo.
#            Retorna um único valor booleano.
array3 = np.array([10,20,30,5])
print(np.array_equal(array1,array2)) # False
print(np.array_equal(array1,array3)) # True

[ 3  6  9 12]
[-1 -2 -3 -4]
[0.5 0.5 0.5 0.5]
[ 2  8 18 32]
[    1    16   729 65536]
[0 0 0 0]
[[3 5 7]
 [2 3 4]]
[3 4 5]
[-1  0  1]
[False False  True False]
[False False False  True]
[ True  True  True False]
False
True


# 15. Filtrando e Buscando Elementos em Arrays
NumPy oferece métodos eficientes para encontrar elementos que satisfazem certas condições.

In [39]:
import numpy
# --- numpy.where() ---
# Propósito: Retorna os ÍNDICES dos elementos que satisfazem uma condição.
#            É muito útil para filtragem de dados.
array = numpy.array([1,3,4,2,7,4])
array_find = numpy.where(array >= 4 ) # Encontra índices onde o valor é maior ou igual a 4.
print(array_find)
# Saída: (array([2, 4, 5]),) (Os elementos nos índices 2, 4 e 5 são >= 4)

# Combinação de condições com operadores lógicos (use & para E, | para OU)
# IMPORTANTE: Em NumPy, para combinar condições booleanas em arrays, você deve usar
#             os operadores bit a bit '&' (AND) e '|' (OR), não 'and' e 'or' do Python,
#             que funcionam apenas em valores booleanos escalares.
array_find = numpy.where( (array == 4) | (array == 7) ) # Índices onde o valor é 4 OU 7.
print(array_find)
# Saída: (array([2, 4, 5]),) (Os elementos nos índices 2, 4 e 5 são 4 ou 7)

array = numpy.array([1,-1,-3,0,6,3,-78])
array_find = numpy.where( (array > 0) & (array < 10) ) # Índices onde o valor é > 0 E < 10.
print(array_find)
# Saída: (array([0, 4, 5]),) (Os elementos nos índices 0, 4 e 5 são 1, 6 e 3)

# --- numpy.any() e numpy.all() ---
# Propósito:
# numpy.any(): Retorna True se *qualquer* elemento no array (ou ao longo de um eixo)
#              satisfaz uma condição. Útil para verificar a existência de algo.
# numpy.all(): Retorna True se *TODOS* os elementos no array (ou ao longo de um eixo)
#              satisfazem uma condição. Útil para verificar a uniformidade.

# Exemplo com numpy.any()
data_array = np.array([10, 20, 30, 5, -1])
condition_any = data_array < 0
print(f"Existe algum número negativo no array? {np.any(condition_any)}") # Saída: True

# Exemplo com numpy.all()
condition_all = data_array > 0
print(f"Todos os números são positivos no array? {np.all(condition_all)}") # Saída: False (por causa do -1)


(array([2, 4, 5]),)
(array([2, 4, 5]),)
(array([0, 4, 5]),)
Existe algum número negativo no array? True
Todos os números são positivos no array? False


# 16. Ordenação de Arrays
Ordenar elementos em um array é uma operação comum para análise e apresentação de dados. NumPy oferece funções eficientes para isso.

In [48]:
import numpy

# --- numpy.sort() ---
# numpy.sort(array, axis=-1, kind='quicksort', order=None)
# Retorna uma CÓPIA ordenada do array. O array original NÃO é modificado.
# 'kind' especifica o algoritmo de ordenação (ex: 'quicksort', 'mergesort', 'heapsort').
# Por padrão, `axis=-1` significa que a ordenação ocorre ao longo do último eixo (para arrays 1D, é o único eixo).

array = numpy.array([4,1,3,2])
print(numpy.sort(array, kind='quicksort')) # Saída: [1 2 3 4]
print(array) # Saída: [4 1 3 2] (array original inalterado)

# Ordenando Arrays 2D
# `axis`: controla ao longo de qual dimensão a ordenação será aplicada.
# axis=0: Ordena ao longo das COLUNAS. Cada coluna é ordenada independentemente.
# axis=1: Ordena ao longo das LINHAS. Cada linha é ordenada independentemente.
array = numpy.array([[38,2,1],[5,5,4]])
print(array)
# Saída:
# [[38  2  1]
#  [ 5  5  4]]

print(numpy.sort(array, axis = 0 )) # Ordena colunas (a ordenação ocorre "para baixo" em cada coluna)
# Saída:
# [[ 5  2  1]  (Coluna 0: [38,5] -> [5,38])
#  [38  5  4]] (Coluna 1: [2,5]  -> [2,5])
              # (Coluna 2: [1,4]  -> [1,4])

print(numpy.sort(array, axis = 1 )) # Ordena linhas (a ordenação ocorre "através" de cada linha)
# Saída:
# [[ 1  2 38] (Linha 0: [38,2,1] -> [1,2,38])
#  [ 4  5  5]] (Linha 1: [5,5,4]  -> [4,5,5])


[1 2 3 4]
[4 1 3 2]
[[38  2  1]
 [ 5  5  4]]
[[ 5  2  1]
 [38  5  4]]
[[ 1  2 38]
 [ 4  5  5]]


In [49]:
#Informações Adicionais e Aprofundamento:

#Ordenação no Local (.sort()): Além de np.sort(), que retorna uma cópia, os objetos ndarray também têm um método .sort() que ordena o array no local (modifica o array original e não retorna nada).

import numpy as np # Importa NumPy com o apelido padrão np

arr = np.array([4,1,3,2])
arr.sort() # Modifica o array 'arr' diretamente
print(arr) # Saída: [1 2 3 4]

[1 2 3 4]


In [51]:
# argsort(): Se você precisar dos índices que ordenariam o array (em vez dos valores ordenados), use np.argsort(). Isso é útil para reordenar outros arrays com base na ordem de um array específico.

In [52]:
import numpy as np # Importa NumPy com o apelido padrão np

arr = np.array([4,1,3,2])
indices_ordenados = np.argsort(arr) # Retorna os índices que ordenariam o array
print(indices_ordenados) # Saída: [1 3 2 0] (O elemento no índice 1 (valor 1) vem primeiro, depois o do índice 3 (valor 2), etc.)
print(arr[indices_ordenados]) # Saída: [1 2 3 4] (Usando os índices para acessar o array original na ordem ordenada)

[1 3 2 0]
[1 2 3 4]


In [53]:
# Ordenação de Arrays Estruturados: Para arrays com dtype composto (como o tipo_pessoa que vimos anteriormente), você pode ordenar por um campo específico usando o parâmetro order.
import numpy as np # Importa NumPy com o apelido padrão np

# Relembrando a definição de tipo_pessoa
tipo_pessoa = np.dtype([ ('nome','S10'),('idade','i4') ])
data = np.array([('Rodrigo', 24), ('fernando', 45), ('Ana', 30)], dtype=tipo_pessoa)
print(data)
# Saída: [(b'Rodrigo', 24) (b'fernando', 45) (b'Ana', 30)]

sorted_by_name = np.sort(data, order='nome') # Ordena pelo campo 'nome'
print(sorted_by_name)
# Saída: [(b'Ana', 30) (b'Rodrigo', 24) (b'fernando', 45)] (Strings de bytes são ordenadas lexicograficamente)

sorted_by_age = np.sort(data, order='idade') # Ordena pelo campo 'idade'
print(sorted_by_age)
# Saída: [(b'Rodrigo', 24) (b'Ana', 30) (b'fernando', 45)]

[(b'Rodrigo', 24) (b'fernando', 45) (b'Ana', 30)]
[(b'Ana', 30) (b'Rodrigo', 24) (b'fernando', 45)]
[(b'Rodrigo', 24) (b'Ana', 30) (b'fernando', 45)]


# 17. Funções Universais (ufuncs) e Operações Matemáticas Avançadas
As Funções Universais (ufuncs) são o pilar da computação numérica eficiente no NumPy. Elas são funções que operam elemento a elemento em arrays, suportam broadcasting e são implementadas em C para altíssima performance. Os operadores aritméticos (+, -, *, /) são, na verdade, atalhos para ufuncs correspondentes (np.add, np.subtract, etc.).

In [67]:

# --- Operações Aritméticas Básicas (com ufuncs explícitos) ---
# Você pode usar os operadores (+, -, *, /) diretamente ou as funções ufunc equivalentes.
# As ufuncs são úteis quando você precisa de mais controle (ex: `out` para especificar onde o resultado
# será armazenado) ou para operações mais complexas que não têm um operador direto.
arr1 = numpy.array([1,2,3,4,5,6,18])
arr2 = numpy.array([1,2,3,4,5,6,3])
array1 = numpy.add(arr1, arr2)      # Soma elemento a elemento
array2 = numpy.subtract(arr1, arr2) # Subtração elemento a elemento
array3 = numpy.multiply(arr1, arr2) # Multiplicação elemento a elemento
array4 = numpy.divide(arr1, arr2)   # Divisão elemento a elemento (retorna floats)

print(f"Soma (add): {array1}")      # Saída: [ 2  4  6  8 10 12 21]
print(f"Subtração (subtract): {array2}") # Saída: [0 0 0 0 0 0 15]
print(f"Multiplicação (multiply): {array3}") # Saída: [ 1  4  9 16 25 36 54]
print(f"Divisão (divide): {array4}")   # Saída: [ 1.          1.          1.

# --- Operações Aritméticas com Matrizes ---
# As ufuncs também funcionam elemento a elemento com matrizes, aplicando broadcasting se as formas forem compatíveis.
arr1 = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
array = numpy.add(arr1, arr2) # Soma as duas matrizes elemento a elemento.

print(f"\nSoma de Matrizes:\n{array}")
# Saída:
# [[ 2  4  6]
#  [ 8 10 12]
#  [14 16 18]]

# --- Divisão Inteira (Floor Division) ---
arr1 = numpy.array([1,2,3,4,5,6,18])
arr2 = numpy.array([1,2,3,4,5,6,3])

array1 = numpy.divide(arr1, arr2)       # Divisão normal (flutuante)
array2 = numpy.floor_divide(arr1, arr2) # Divisão inteira (descarta a parte decimal, arredonda para o inteiro mais próximo em direção ao infinito negativo)
print(f"\nDivisão normal: {array1}") # Saída: [ 1.          1.          1.          1.          1.          1.          6.]
print(f"Divisão inteira (floor_divide): {array2}") # Saída: [1 1 1 1 1 1 6]

# --- Potenciação (Power) ---
arr1 = numpy.array([1,2])
arr2 = numpy.array([2,4])

array1 = numpy.power(arr1, arr2) # Eleva o primeiro array ao poder do segundo array (elemento a elemento).
print(f"\nPotenciação (power): {array1}") # Saída: [ 1 16] (1^2=1, 2^4=16)

# --- Módulo (Resto da Divisão) ---
arr1 = numpy.array([2,2,100])
arr2 = numpy.array([2,3,31])

array1 = numpy.mod(arr1, arr2) # Calcula o resto da divisão elemento a elemento.
print(f"\nMódulo (mod): {array1}") # Saída: [0 2  7] (2%2=0, 2%3=2, 100%31=7)

# --- Divisão e Módulo Juntos (divmod) ---
# Retorna uma tupla de dois arrays: (quociente inteiro, resto). Mais eficiente do que calcular separadamente.
array1 = numpy.divmod(arr1, arr2)
print(f"Divisão e Módulo (divmod): {array1}")

# --- Raiz Quadrada (sqrt) ---
arr1 = numpy.array([4,25,100])
array1 = numpy.sqrt(arr1) # Calcula a raiz quadrada de cada elemento.
print(f"\nRaiz Quadrada (sqrt): {array1}") # Saída: [ 2.  5. 10.]

# --- Funções de Arredondamento (around, floor, ceil, trunc, rint) ---
# Existem várias ufuncs para arredondamento com diferentes comportamentos.
arr1 = numpy.array([3.14159, 2.71, -1.5, -2.9])

# numpy.around(array, decimals=0): Arredonda para o número de casas decimais especificado.
# Arredonda para o inteiro mais próximo; .5 é arredondado para o inteiro par mais próximo.
array_around = numpy.around(arr1, 2) # Arredonda para 2 casas decimais.
print(f"\naround (2 casas): {array_around}") # Saída: [3.14 2.71 -1.5  -2.9 ]

# numpy.around(array, decimals=0): Arredonda para o número de casas decimais especificado.
# Arredonda para o inteiro mais próximo; .5 é arredondado para o inteiro par mais próximo.
array_around = numpy.around(arr1, 2) # Arredonda para 2 casas decimais.
print(f"\naround (2 casas): {array_around}") # Saída: [3.14 2.71 -1.5  -2.9 ]

# numpy.floor(array): Arredonda para baixo (para o inteiro mais próximo em direção ao infinito negativo).
array_floor = numpy.floor(arr1)
print(f"floor: {array_floor}") # Saída: [ 3.  2. -2. -3.]

# numpy.ceil(array): Arredonda para cima (para o inteiro mais próximo em direção ao infinito positivo).
array_ceil = numpy.ceil(arr1)
print(f"ceil: {array_ceil}") # Saída: [ 4.  3. -1. -2.]

# numpy.trunc(array): Trunca (remove a parte decimal, em direção a zero).
array_trunc = numpy.trunc(arr1)
print(f"trunc: {array_trunc}") # Saída: [ 3.  2. -1. -2.]

# numpy.rint(array): Arredonda para o inteiro mais próximo. .5 é arredondado para o inteiro par mais próximo.
array_rint = numpy.rint(arr1)
print(f"rint: {array_rint}") # Saída: [ 3.  3. -2. -3.]

Soma (add): [ 2  4  6  8 10 12 21]
Subtração (subtract): [ 0  0  0  0  0  0 15]
Multiplicação (multiply): [ 1  4  9 16 25 36 54]
Divisão (divide): [1. 1. 1. 1. 1. 1. 6.]

Soma de Matrizes:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Divisão normal: [1. 1. 1. 1. 1. 1. 6.]
Divisão inteira (floor_divide): [1 1 1 1 1 1 6]

Potenciação (power): [ 1 16]

Módulo (mod): [0 2 7]
Divisão e Módulo (divmod): (array([1, 0, 3]), array([0, 2, 7]))

Raiz Quadrada (sqrt): [ 2.  5. 10.]

around (2 casas): [ 3.14  2.71 -1.5  -2.9 ]

around (2 casas): [ 3.14  2.71 -1.5  -2.9 ]
floor: [ 3.  2. -2. -3.]
ceil: [ 4.  3. -1. -2.]
trunc: [ 3.  2. -1. -2.]
rint: [ 3.  3. -2. -3.]


Informações Adicionais e Aprofundamento:

Vetorização e Speed-up: A principal vantagem das ufuncs é a velocidade. Ao operar diretamente em arrays (em C), elas evitam o overhead dos loops Python, tornando-as ideais para operações numéricas em grandes datasets.

Lista Abrangente de Ufuncs: O NumPy possui centenas de ufuncs para diversas operações:

Trigonométricas: sin, cos, tan, arcsin, arccos, arctan, etc.

Exponenciais e Logarítmicas: exp, log, log2, log10, expm1, log1p.

Comparação: equal, not_equal, greater, less, greater_equal, less_equal.

Bitwise: bitwise_and, bitwise_or, bitwise_xor, invert, left_shift, right_shift.

Outras: absolute, sign, maximum, minimum, clip.

Parâmetros Opcionais de Ufuncs: Muitas ufuncs aceitam parâmetros como out (para especificar um array existente onde o resultado deve ser armazenado, evitando alocação de nova memória) e where (para aplicar a operação condicionalmente).

# 18. Funções Agregadas (Soma, Produto, Mínimo, Máximo, Absoluto)
Funções agregadas (ou de redução) calculam um único valor (ou um array de valores reduzidos) a partir dos elementos de um array, como a soma de todos os elementos, o valor mínimo, o desvio padrão, etc. O uso do parâmetro axis é fundamental para controlar a dimensão ao longo da qual a agregação é realizada.

In [76]:
import numpy

# --- Soma de Elementos (sum) ---
# numpy.sum(array, axis=None, dtype=None, out=None, keepdims=False)
# `axis=None` (padrão): Soma todos os elementos do array, resultando em um escalar.
array = numpy.array([[1,2,3],[4,5,6]])
array_sum = numpy.sum(array) # Soma todos os elementos do array.
print(f"Soma total do array: {array_sum}") # Saída: 21 (1+2+3+4+5+6)

# Soma ao longo de um eixo
# `axis=0`: Soma ao longo das LINHAS (colunas são agregadas). O resultado terá um elemento para cada coluna.
# `axis=1`: Soma ao longo das COLUNAS (linhas são agregadas). O resultado terá um elemento para cada linha.
array_sum_row = numpy.sum(array, axis = 1) # Soma ao longo das LINHAS (o resultado tem um valor por linha).
print(f"Soma por linha: {array_sum_row}") # Saída: [ 6 15] (1+2+3=6, 4+5+6=15)

array_sum_col = numpy.sum(array, axis=0) # Soma ao longo das COLUNAS (o resultado tem um valor por coluna).
print(f"Soma por coluna: {array_sum_col}") # Saída: [5 7 9] (1+4=5, 2+5=7, 3+6=9)

# --- Soma Cumulativa (cumsum) ---
# numpy.cumsum(array, axis=None, dtype=None, out=None)
# Retorna um array com a soma cumulativa dos elementos.
# Se `axis=None`, o array é achatado e a soma cumulativa é calculada sequencialmente.
array_sum_cumulative = numpy.cumsum(array) # Achata o array e soma cumulativamente.
print(f"\nSoma cumulativa (achatado): {array_sum_cumulative}") # Saída: [ 1  3  6 10 15 21] (1, 1+2, 1+2+3, 1+2+3+4, ...)

# --- Produto Cumulativo (cumprod) ---
# numpy.cumprod(array, axis=None, dtype=None, out=None)
# Retorna um array com o produto cumulativo dos elementos.
# Se `axis=None`, o array é achatado e o produto cumulativo é calculado sequencialmente.
array_prod_cumulative = numpy.cumprod(array) # Achata o array e multiplica cumulativamente.
print(f"\nProduto cumulativo (achatado): {array_prod_cumulative}") # Saída: [  1   2   6  24 120 720] (1, 1*2, 1*2*3, 1*2*3*4, ...)

# Produto Cumulativo ao longo de um eixo
array1_cumprod_axis0 = numpy.cumprod(array, axis =0) # Produto cumulativo por coluna (cada coluna é processada independentemente).
print(f"\nProduto cumulativo por coluna:\n{array1_cumprod_axis0}")
# Saída:
# [[ 1  2  3]   (Primeira linha inalterada)
#  [ 4 10 18]] (Produto cumulativo da coluna 0: [1, 1*4=4], Coluna 1: [2, 2*5=10], Coluna 2: [3, 3*6=18])

array2_cumprod_axis1 = numpy.cumprod(array, axis =1) # Produto cumulativo por linha (cada linha é processada independentemente).
print(f"Produto cumulativo por linha:\n{array2_cumprod_axis1}")
# Saída:
# [[ 1  2  6]   (Linha 0: 1, 1*2, 1*2*3)
#  [ 4 20 120]] (Linha 1: 4, 4*5, 4*5*6)

# --- Mínimo e Máximo (amin, amax, min, max) ---
# Encontra o valor mínimo ou máximo no array.
# Você pode usar as funções globais `np.amin()`, `np.amax()` ou os métodos de array `.min()`, `.max()`.
array_single_row = numpy.array([[1,2,3,4,5,6]])
print(f"\nMínimo de todo o array (np.amin): {numpy.amin(array_single_row)}") # Mínimo em todo o array - Saída: 1
print(f"Máximo de todo o array (np.amax): {numpy.amax(array_single_row)}") # Máximo em todo o array - Saída: 6

# Valor Absoluto (abs)
# numpy.abs(array): Retorna o valor absoluto de cada elemento. É uma ufunc.
array_with_negatives = numpy.array([[1,-2,-3,-4,5,6]])
print(f"\nValores absolutos (np.abs): {numpy.abs(array_with_negatives)}") # Saída: [[1 2 3 4 5 6]]


# Mínimo e Máximo ao longo de um eixo
array_2d = numpy.array([[1,4,8],[4,3,6]])
print(f"\nArray 2D original:\n{array_2d}")
# Saída:
# [[1 4 8]
#  [4 3 6]]
print(f"Mínimo de todo o array: {numpy.amin(array_2d)}")       # Mínimo de todo o array - Saída: 1
print(f"Mínimo por linha (axis=1): {numpy.amin(array_2d, axis = 1)}") # Mínimo por linha (agregando colunas) - Saída: [1 3] (min(1,4,8)=1, min(4,3,6)=3)
print(f"Mínimo por coluna (axis=0): {numpy.amin(array_2d, axis = 0)}") # Mínimo por coluna (agregando linhas) - Saída: [1 3 6] (min(1,4)=1, min(4,3)=3, min(8,6)=6)


Soma total do array: 21
Soma por linha: [ 6 15]
Soma por coluna: [5 7 9]

Soma cumulativa (achatado): [ 1  3  6 10 15 21]

Produto cumulativo (achatado): [  1   2   6  24 120 720]

Produto cumulativo por coluna:
[[ 1  2  3]
 [ 4 10 18]]
Produto cumulativo por linha:
[[  1   2   6]
 [  4  20 120]]

Mínimo de todo o array (np.amin): 1
Máximo de todo o array (np.amax): 6

Valores absolutos (np.abs): [[1 2 3 4 5 6]]

Array 2D original:
[[1 4 8]
 [4 3 6]]
Mínimo de todo o array: 1
Mínimo por linha (axis=1): [1 3]
Mínimo por coluna (axis=0): [1 3 6]


# 19. Operações de Conjunto (Set Operations)
NumPy fornece funções eficientes para realizar operações de conjunto em arrays 1D. Essas funções tratam os arrays como coleções de elementos, ignorando a ordem e duplicatas para a maioria das operações.

In [83]:
import numpy

# --- União (union1d) ---
# numpy.union1d(ar1, ar2): Retorna os elementos únicos que estão em um OU em outro array, ordenados.
# Trata os arrays como conjuntos matemáticos.
arr1 = numpy.array([1,2,3,4])
arr2 = numpy.array([3,4,5,6,7])
newarr_union = numpy.union1d(arr1,arr2)
print(f"União: {newarr_union}") # Saída: [1 2 3 4 5 6 7]

# --- Intersecção (intersect1d) ---
# numpy.intersect1d(ar1, ar2, assume_unique=False): Retorna os elementos únicos que estão em AMBOS os arrays, ordenados.
# `assume_unique=True` pode acelerar a operação se você tiver certeza de que os arrays de entrada já não contêm duplicatas.
arr1 = numpy.array([1,2,3,4])
arr2 = numpy.array([3,4,5,6,7])
newarr_intersect = numpy.intersect1d(arr1,arr2)
print(f"Intersecção: {newarr_intersect}") # Saída: [3 4]

# --- Elementos Únicos (unique) ---
# numpy.unique(array, return_index=False, return_inverse=False, return_counts=False, axis=None)
# Retorna os elementos únicos de um array, ordenados.
# É uma das funções de conjunto mais usadas.
arr1 = numpy.array([1,2,2,3,4,3,5,5,5,4])
newarr_unique = numpy.unique(arr1)
print(f"Elementos Únicos: {newarr_unique}") # Saída: [1 2 3 4 5]

# Você também pode retornar os índices dos elementos únicos e suas contagens:
unique_elements, indices, counts = numpy.unique(arr1, return_index=True, return_counts=True)
print(f"Elementos Únicos (com detalhes): {unique_elements}") # Saída: [1 2 3 4 5]
print(f"Primeiros Índices: {indices}") # Saída: [0 1 3 4 6] (índice da primeira ocorrência de cada elemento único)
print(f"Contagens: {counts}") # Saída: [1 2 2 2 3] (1 aparece 1 vez, 2 aparece 2 vezes, etc.)

# --- Diferença de Conjuntos (setdiff1d) ---
# numpy.setdiff1d(ar1, ar2, assume_unique=False): Retorna os elementos únicos em `ar1` que NÃO estão em `ar2`.
arr1 = numpy.array([1,2,3,4])
arr2 = numpy.array([3,4,5,6,7])
newarr_diff = numpy.setdiff1d(arr1,arr2)
print(f"Diferença (arr1 - arr2): {newarr_diff}") # Saída: [1 2]

# --- Testar Membership (isin) ---
# numpy.isin(element, test_elements, assume_unique=False, invert=False)
# Retorna um array booleano indicando se cada elemento de `element` está presente em `test_elements`.
arr1 = numpy.array([1, 5, 2, 8, 3, 9])
test_elements = [2, 3, 4]
newarr_isin = numpy.isin(arr1, test_elements)
print(f"Está em (isin): {newarr_isin}") # Saída: [False False  True False  True False] (1 não está, 5 não está, 2 está, etc.)

União: [1 2 3 4 5 6 7]
Intersecção: [3 4]
Elementos Únicos: [1 2 3 4 5]
Elementos Únicos (com detalhes): [1 2 3 4 5]
Primeiros Índices: [0 1 3 4 6]
Contagens: [1 2 2 2 3]
Diferença (arr1 - arr2): [1 2]
Está em (isin): [False False  True False  True False]


# Exercícios


Exercício 1: Análise de Dados de Vendas


In [19]:
#Para todos os exercícios, comece com: import numpy as np

#Exercício 1: Análise de Dados de Vendas
#Você tem uma matriz 2D que representa as vendas de três produtos (nas colunas) ao longo de quatro semanas (nas linhas).
import numpy as np 
vendas = np.array([[150, 120, 180],  # Semana 1
                   [160, 135, 190],  # Semana 2
                   [145, 125, 175],  # Semana 3
                   [170, 140, 200]]) # Semana 4

# 1. Cálculo Total: Calcule o total de vendas de cada produto ao longo das quatro semanas. Qual produto vendeu mais no total?
print(f"total das vendas semanais é:", np.sum(vendas, axis=1))

# 2. Média Semanal: Calcule a média de vendas de cada semana.
print(f"média semanal", np.mean(vendas,axis=1))
# 3. Filtragem de Vendas Altas: Use indexação booleana para encontrar e imprimir todas as vendas que foram maiores que 150.
filtro = vendas > 150
print(f"Esses são valores superiores à 150:", vendas[filtro])
# 4.Ajuste de Preço: Imagine que as vendas da semana 3 (vendas[2]) foram feitas com um desconto de 10% e você precisa recalcular o valor total sem o desconto. Multiplique as vendas da semana 3 por 1.1 e imprima o novo vetor.

desconto = vendas[2] * 0.90
ajuste = desconto /0.90
print(f"desconto valores semanais", desconto)
print(f"desconto valores semanais", ajuste)

total das vendas semanais é: [450 485 445 510]
média semanal [150.         161.66666667 148.33333333 170.        ]
Esses são valores superiores à 150: [180 160 190 175 170 200]
desconto valores semanais [130.5 112.5 157.5]
desconto valores semanais [145. 125. 175.]


In [ ]:
Exercício 2: Análise de Notas de Alunos

In [36]:

# Você tem um array 1D que representa as notas de 10 alunos.


import numpy as np

np.random.seed(42) # Usamos uma "semente" para que os resultados aleatórios sejam os mesmos toda vez que rodar o código
notas = np.random.randint(50, 101, 10)

print("Notas dos alunos:", notas)

# 1. Encontrar Aprovados: Assumindo que a nota mínima para aprovação é 70, use np.where() para encontrar os índices dos alunos aprovados.

# 2. Contar Reprovados: Use a indexação booleana para contar quantos alunos foram reprovados (nota < 70).

# 3. Classificar Notas: Crie um novo array booleano que seja True se a nota for maior ou igual a 90, False caso contrário.

# 4. Ordenar e Obter Ranking: Ordene as notas em ordem decrescente. Como você faria para saber o índice do aluno que tirou a maior nota no array original?
resultado = np.where(notas >= 70)
ordenado = notas[resultado]
print(np.sort(ordenado))


Notas dos alunos: [88 78 64 92 57 70 88 68 72 60]
[70 72 78 88 88 92]
resultado fora decrescente: [88 78 92 70 88 72]


correção Exercício 2

In [37]:
import numpy as np

np.random.seed(42)
notas = np.random.randint(50, 101, 10)

print("Notas dos alunos:", notas)
# Saída: [ 82  89  98  90  89  74  59  86  82 100]

# 1. Encontrar Aprovados: Assumindo que a nota mínima para aprovação é 70, use np.where() para encontrar os índices dos alunos aprovados.
# np.where() retorna uma tupla. O primeiro elemento da tupla (índice 0) é o array de índices que queremos.
indices_aprovados = np.where(notas >= 70)

print("\n1. Índices dos alunos aprovados:", indices_aprovados)
# Saída esperada: (array([0, 1, 2, 3, 4, 5, 7, 8, 9]),)
# Para imprimir apenas o array de índices, pode usar: print(indices_aprovados[0])

# 2. Contar Reprovados: Use a indexação booleana para contar quantos alunos foram reprovados (nota < 70).
# A indexação booleana cria um array de True/False.
# Em NumPy, True é tratado como 1 e False como 0.
# Podemos simplesmente somar o array booleano para contar os True.
filtro_reprovados = notas < 70
numero_reprovados = filtro_reprovados.sum() # ou np.sum(filtro_reprovados)

print("\n2. Filtro de reprovados (True se reprovado):", filtro_reprovados)
print("Número de alunos reprovados:", numero_reprovados)
# Saída esperada: 1 (a nota 59 no índice 6)

# 3. Classificar Notas: Crie um novo array booleano que seja True se a nota for maior ou igual a 90, False caso contrário.
filtro_maior_ou_igual_a_90 = notas >= 90

print("\n3. Filtro para notas >= 90:", filtro_maior_ou_igual_a_90)
# Saída esperada: [False False  True  True False False False False False  True]

# 4. Ordenar e Obter Ranking: Ordene as notas em ordem decrescente. Como você faria para saber o índice do aluno que tirou a maior nota no array original?
# Primeiro, usamos argsort para obter os índices que ordenariam o array.
indices_ordenados_crescente = np.argsort(notas)

# Para ordem decrescente, simplesmente revertemos esse array de índices.
indices_ordenados_decrescente = indices_ordenados_crescente[::-1]

# O primeiro índice no array de índices decrescente é o do aluno com a maior nota.
indice_maior_nota = indices_ordenados_decrescente[0]
maior_nota = notas[indice_maior_nota]

print("\n4. Índices para ordenar notas de forma decrescente:", indices_ordenados_decrescente)
print(f"O índice do aluno com a maior nota ({maior_nota}) é:", indice_maior_nota)
# Saída esperada (se a semente 42 for usada): 9 (o aluno com nota 100)

Notas dos alunos: [88 78 64 92 57 70 88 68 72 60]

1. Índices dos alunos aprovados: (array([0, 1, 3, 5, 6, 8]),)

2. Filtro de reprovados (True se reprovado): [False False  True False  True False False  True False  True]
Número de alunos reprovados: 4

3. Filtro para notas >= 90: [False False False  True False False False False False False]

4. Índices para ordenar notas de forma decrescente: [3 6 0 1 8 5 7 2 9 4]
O índice do aluno com a maior nota (92) é: 3
